# Generated by Django 3.1.3 on 2020-12-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0013_auto_20201214_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
