# Generated by Django 3.1.3 on 2020-12-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0014_question_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='college_loc',
            field=models.CharField(choices=[('On Campus', 'On Campus'), ('Off Campus', 'Off Campus'), ('At Home', 'At Home')], default='At Home', max_length=10),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='on_campus_housing',
            field=models.CharField(choices=[('Quad', 'Quad'), ('Hill', 'Hill'), ('Gregory', 'Gregory'), ('Rodin', 'Rodin'), ('Harrison', 'Harrison'), ('Harnwell', 'Harnwell'), ('Lauder', 'Lauder'), ('NCWH', 'New College House West'), ('Stouffer', 'Stouffer'), ('Dubois', 'Dubois'), ('NA', 'NA')], default='NA', max_length=10),
        ),
    ]
